### ISSUE TITLE
NASifier script not working with a Synology drive and Sonoma 14.2.1

### ISSUE THREAD

**Issue by mfedoseev** [EricFromCanada/byte-bucket#1]
Hi. Found your blog post on Time Machine migration — looked promising! Tried to use the script to move some older backups to a Synology NAS disk. Getting some errors and the image is not being created:
`$ /Volumes/Backups/Time-Machine-NASifier.command`
`/Volumes/Backups/Time-Machine-NASifier.command: line 1: cd: "/Volumes/Backups": No such file or directory`
`sed: 1: "s/\": unterminated substitute pattern`
`sed: 1: "s/\": unterminated substitute pattern`
`sed: 1: "s/\": unterminated substitute pattern`
`/Volumes/Backups/Time-Machine-NASifier.command: line 1: payload:allShortcutsEnabled:false: command not found`

Can you please assist?

**Comment by mfedoseev** [comment]
Oops! Turns out, unlike the blog link, the file from your GitHub does work. The .sparsebundle was created. False alarm. Thank you for your work!

**Comment by EricFromCanada** [comment]
Great to hear! Always nice to read about my work being useful. Am curious as to what blog link you refer to.

**Comment by mfedoseev** [comment]
Thanks, I first downloaded from a link here: https://ericfromcanada.github.io/output/2021/migrating-time-machine-backups-to-network.html — then also found it on your GitHub.

Though I just compared changes and it looks like the two files are the same…
